//! The cue words distillation, inference and retrieval read documents by.
//!
//! Moved here unchanged from `distill` and `infer`, which re-import them,
//! so the evidence index scores a block with exactly the words the digest
//! and validation already use. A list lives once.

/// Cues that identify what kind of document this is.
pub const TYPE_CUES: &[&str] = &[
    "agreement",
    "amendment",
    "addendum",
    "assignment",
    "certificate",
    "complaint",
    "consent",
    "contract",
    "deed",
    "engagement letter",
    "invoice",
    "lease",
    "letter of intent",
    "memorandum",
    "motion",
    "notice of",
    "order form",
    "packing slip",
    "policy",
    "purchase order",
    "quote",
    "receipt",
    "release",
    "resolution",
    "settlement",
    "statement of work",
    "subpoena",
    "term sheet",
    "termination",
    "waiver",
    "work order",
];

/// Cues that identify who the document is between.
pub const PARTY_CUES: &[&str] = &[
    "by and between",
    "by and among",
    "between",
    "among",
    "this agreement is",
    "the parties",
    "attn:",
    "attention:",
    "to:",
    "from:",
    "client:",
    "customer:",
    "vendor:",
    "supplier:",
    "contractor:",
    "employer:",
    "employee:",
    "landlord:",
    "tenant:",
    "bill to:",
    "sold to:",
    "remit to:",
    "d/b/a",
    " inc",
    " llc",
    " l.l.c",
    " ltd",
    " llp",
    " plc",
    " corporation",
    " corp",
    " company",
    " gmbh",
    " co.",
];

/// Cues that mark the block where a date's meaning is stated.
pub const DATE_ROLE_CUES: &[&str] = &[
    "effective date",
    "effective as of",
    "dated as of",
    "made as of",
    "entered into as of",
    "commencement date",
    "start date",
    "end date",
    "expiration date",
    "termination date",
    "terminates on",
    "notice date",
    "date of this notice",
    "invoice date",
    "issue date",
    "issued on",
    "date of issuance",
    "filed on",
    "filing date",
    "executed on",
    "signed on",
    "date signed",
    "as of the",
    "amendment date",
    "amended as of",
];

/// Cues that mark the subject or matter of the document.
pub const SUBJECT_CUES: &[&str] = &[
    "re:",
    "subject:",
    "matter:",
    "project:",
    "regarding",
    "invoice no",
    "invoice #",
    "sow no",
    "sow #",
    "order no",
    "case no",
    "matter no",
    "reference:",
    "purpose",
    "scope of work",
    "services to be provided",
    "deliverables",
];

/// Cues that mark a signature block.
pub const SIGNATURE_CUES: &[&str] = &[
    "in witness whereof",
    "signature",
    "signed:",
    "by: ",
    "name: ",
    "title: ",
    "printed name",
    "authorized representative",
    "/s/",
];

/// Clause headings whose bodies are near-identical across every contract and
/// therefore carry almost no identifying information.
pub const BOILERPLATE_CUES: &[&str] = &[
    "governing law",
    "severability",
    "entire agreement",
    "counterparts",
    "force majeure",
    "no waiver",
    "waiver of",
    "assignment and",
    "successors and assigns",
    "third-party beneficiaries",
    "third party beneficiaries",
    "headings",
    "survival",
    "notices shall be",
    "dispute resolution",
    "arbitration",
    "limitation of liability",
    "indemnification",
    "compliance with law",
    "further assurances",
    "relationship of the parties",
    "independent contractor status",
    "no partnership",
    "interpretation",
    "construction",
];

/// Words that make a heading the name of a kind of document.
pub const TYPE_NOUNS: &[&str] = &[
    "agreement",
    "amendment",
    "addendum",
    "contract",
    "lease",
    "invoice",
    "receipt",
    "order",
    "slip",
    "statement",
    "notice",
    "letter",
    "memorandum",
    "memo",
    "minutes",
    "journal",
    "report",
    "certificate",
    "policy",
    "proposal",
    "quote",
    "quotation",
    "estimate",
    "resolution",
    "agenda",
    "plan",
    "checklist",
    "form",
    "application",
    "specification",
    "review",
    "assessment",
    "audit",
    "license",
    "licence",
    "permit",
    "deed",
    "affidavit",
    "declaration",
    "complaint",
    "motion",
    "subpoena",
    "waiver",
    "release",
    "consent",
    "authorization",
    "authorisation",
    "warranty",
    "guarantee",
    "bond",
    "log",
    "transcript",
    "brief",
    "opinion",
    "ruling",
    "judgment",
    "decree",
    "manual",
    "guide",
    "handbook",
    "protocol",
    "procedure",
    "bill",
    "ticket",
    "itinerary",
    "budget",
    "forecast",
    "ledger",
    "roster",
    "register",
    "inventory",
    "newsletter",
    "bulletin",
    "announcement",
    "summary",
    "evaluation",
    "questionnaire",
    "survey",
    "registration",
    "renewal",
    "termination",
    "offer",
    "engagement",
    "confirmation",
    "acknowledgement",
    "acknowledgment",
    // Initialisms that are document kinds in their own right.
    "nda",
    "sow",
    "msa",
    "mou",
    "loi",
    "rfp",
    "rfq",
    "sla",
    "eula",
    "dpa",
];

/// Headings that head a part of a document, never the document.
pub const NOT_A_TITLE: &[&str] = &[
    "confidential",
    "exhibit",
    "schedule",
    "appendix",
    "annex",
    "attachment",
    "table of contents",
    "contents",
    "page",
    "draft",
    "article",
    "section",
    "recitals",
    "whereas",
    "definitions",
    "signature",
    "signatures",
    "in witness whereof",
    "background",
    "introduction",
    "re:",
    "subject:",
    "to:",
    "from:",
    "cc:",
    "date:",
    "privileged",
    "sample",
    "copy",
];

/// Wording that names the customer of an issued document: who it is billed,
/// sold, shipped or addressed to.
pub const CUSTOMER_CUES: &[&str] = &[
    "bill to",
    "billed to",
    "sold to",
    "ship to",
    "invoice to",
    "customer",
    "client",
    "buyer",
    "purchaser",
    "attn",
    "attention",
    "prepared for",
    "deliver to",
    "consignee",
];

/// Wording that names who issued a document: where payment goes, who sold
/// or prepared it.
pub const ISSUER_CUES: &[&str] = &[
    "remit to",
    "remittance",
    "payable to",
    "from:",
    "vendor",
    "supplier",
    "seller",
    "issued by",
    "prepared by",
];
