//! The cue words distillation, inference and retrieval read documents by.
//!
//! Moved here unchanged from `distill` and `infer`, which re-import them,
//! so the evidence index scores a block with exactly the words the digest
//! and validation already use. A list lives once.

/// Cues that identify what kind of document this is.
pub const TYPE_CUES: &[&str] = &[
    "agreement",
    "amendment",
    "addendum",
    "assignment",
    "certificate",
    "complaint",
    "consent",
    "contract",
    "deed",
    "engagement letter",
    "invoice",
    "lease",
    "letter of intent",
    "memorandum",
    "motion",
    "notice of",
    "order form",
    "packing slip",
    "policy",
    "purchase order",
    "quote",
    "receipt",
    "release",
    "resolution",
    "settlement",
    "statement of work",
    "subpoena",
    "term sheet",
    "termination",
    "waiver",
    "work order",
];

/// Cues that identify who the document is between.
pub const PARTY_CUES: &[&str] = &[
    "by and between",
    "by and among",
    "between",
    "among",
    "this agreement is",
    "the parties",
    "attn:",
    "attention:",
    "to:",
    "from:",
    "client:",
    "customer:",
    "vendor:",
    "supplier:",
    "contractor:",
    "employer:",
    "employee:",
    "landlord:",
    "tenant:",
    "bill to:",
    "sold to:",
    "remit to:",
    "d/b/a",
    " inc",
    " llc",
    " l.l.c",
    " ltd",
    " llp",
    " plc",
    " corporation",
    " corp",
    " company",
    " gmbh",
    " co.",
];

/// Cues that mark the block where a date's meaning is stated.
pub const DATE_ROLE_CUES: &[&str] = &[
    "effective date",
    "effective as of",
    "dated as of",
    "made as of",
    "entered into as of",
    "commencement date",
    "start date",
    "end date",
    "expiration date",
    "termination date",
    "terminates on",
    "notice date",
    "date of this notice",
    "invoice date",
    "issue date",
    "issued on",
    "date of issuance",
    "filed on",
    "filing date",
    "executed on",
    "signed on",
    "date signed",
    "as of the",
    "amendment date",
    "amended as of",
];

/// Cues that mark the subject or matter of the document.
pub const SUBJECT_CUES: &[&str] = &[
    "re:",
    "subject:",
    "matter:",
    "project:",
    "regarding",
    "invoice no",
    "invoice #",
    "sow no",
    "sow #",
    "order no",
    "case no",
    "matter no",
    "reference:",
    "purpose",
    "scope of work",
    "services to be provided",
    "deliverables",
];

/// Cues that mark a signature block.
pub const SIGNATURE_CUES: &[&str] = &[
    "in witness whereof",
    "signature",
    "signed:",
    "by: ",
    "name: ",
    "title: ",
    "printed name",
    "authorized representative",
    "/s/",
];

/// Clause headings whose bodies are near-identical across every contract and
/// therefore carry almost no identifying information.
pub const BOILERPLATE_CUES: &[&str] = &[
    "governing law",
    "severability",
    "entire agreement",
    "counterparts",
    "force majeure",
    "no waiver",
    "waiver of",
    "assignment and",
    "successors and assigns",
    "third-party beneficiaries",
    "third party beneficiaries",
    "headings",
    "survival",
    "notices shall be",
    "dispute resolution",
    "arbitration",
    "limitation of liability",
    "indemnification",
    "compliance with law",
    "further assurances",
    "relationship of the parties",
    "independent contractor status",
    "no partnership",
    "interpretation",
    "construction",
];

/// Words that make a heading the name of a kind of document.
pub const TYPE_NOUNS: &[&str] = &[
    "agreement",
    "amendment",
    "addendum",
    "contract",
    "lease",
    "invoice",
    "receipt",
    "order",
    "slip",
    "statement",
    "notice",
    "letter",
    "memorandum",
    "memo",
    "minutes",
    "journal",
    "report",
    "certificate",
    "policy",
    "proposal",
    "quote",
    "quotation",
    "estimate",
    "resolution",
    "agenda",
    "plan",
    "checklist",
    "form",
    "application",
    "specification",
    "review",
    "assessment",
    "audit",
    "license",
    "licence",
    "permit",
    "deed",
    "affidavit",
    "declaration",
    "complaint",
    "motion",
    "subpoena",
    "waiver",
    "release",
    "consent",
    "authorization",
    "authorisation",
    "warranty",
    "guarantee",
    "bond",
    "log",
    "transcript",
    "brief",
    "opinion",
    "ruling",
    "judgment",
    "decree",
    "manual",
    "guide",
    "handbook",
    "protocol",
    "procedure",
    "bill",
    "ticket",
    "itinerary",
    "budget",
    "forecast",
    "ledger",
    "roster",
    "register",
    "inventory",
    "newsletter",
    "bulletin",
    "announcement",
    "summary",
    "evaluation",
    "questionnaire",
    "survey",
    "registration",
    "renewal",
    "termination",
    "offer",
    "engagement",
    "confirmation",
    "acknowledgement",
    "acknowledgment",
    // Initialisms that are document kinds in their own right.
    "nda",
    "sow",
    "msa",
    "mou",
    "loi",
    "rfp",
    "rfq",
    "sla",
    "eula",
    "dpa",
];

/// Headings that head a part of a document, never the document.
pub const NOT_A_TITLE: &[&str] = &[
    "confidential",
    "exhibit",
    "schedule",
    "appendix",
    "annex",
    "attachment",
    "table of contents",
    "contents",
    "page",
    "draft",
    "article",
    "section",
    "recitals",
    "whereas",
    "definitions",
    "signature",
    "signatures",
    "in witness whereof",
    "background",
    "introduction",
    "re:",
    "subject:",
    "to:",
    "from:",
    "cc:",
    "date:",
    "privileged",
    "sample",
    "copy",
];

/// Wording that names the customer of an issued document: who it is billed,
/// sold, shipped or addressed to.
pub const CUSTOMER_CUES: &[&str] = &[
    "bill to",
    "billed to",
    "sold to",
    "ship to",
    "invoice to",
    "customer",
    "client",
    "buyer",
    "purchaser",
    "attn",
    "attention",
    "prepared for",
    "deliver to",
    "consignee",
];

/// Wording that names who issued a document: where payment goes, who sold
/// or prepared it.
pub const ISSUER_CUES: &[&str] = &[
    "remit to",
    "remittance",
    "payable to",
    "from:",
    "vendor",
    "supplier",
    "seller",
    "issued by",
    "prepared by",
];

// What follows is read only by the evidence index and the retriever.

/// The words a company's or an institution's name ends on: legal forms
/// ("Inc", "LLC", "N.A.") and the nouns an organisation calls itself by
/// ("Bank", "Cooperative", "Authority"). Compared without case or trailing
/// punctuation; a likely organisation is a run of capitalised words ending
/// on one, so recall matters more here than precision.
pub const ORGANISATION_ENDINGS: &[&str] = &[
    "inc",
    "incorporated",
    "llc",
    "l.l.c",
    "ltd",
    "limited",
    "corp",
    "corporation",
    "co",
    "company",
    "llp",
    "l.l.p",
    "lp",
    "l.p",
    "pllc",
    "plc",
    "pc",
    "p.c",
    "n.a",
    "gmbh",
    "ag",
    "s.a",
    "n.v",
    "b.v",
    "pty",
    "bank",
    "cooperative",
    "co-op",
    "association",
    "authority",
    "district",
    "union",
    "partners",
    "partnership",
    "holdings",
    "group",
    "trust",
    "fund",
    "foundation",
    "society",
    "club",
    "institute",
    "university",
    "college",
    "school",
    "hospital",
    "clinic",
    "museum",
    "library",
    "council",
    "county",
    "agency",
    "department",
    "services",
    "systems",
    "labs",
    "laboratories",
    "works",
    "supply",
    "properties",
    "industries",
    "enterprises",
    "ventures",
    "associates",
    "solutions",
    "distributors",
    "growers",
    "grocers",
    "vineyards",
    "nursery",
    "gallery",
    "graphics",
    "brokerage",
    "outfitters",
    "builders",
    "contractors",
    "cpas",
    "feed",
];

/// Courtesy titles that open a person's name.
pub const HONORIFICS: &[&str] = &["mr", "mrs", "ms", "miss", "mx", "dr", "prof"];

/// Labels whose value is a person or a party: `Tenant: Paloma Iwasaki`,
/// `Bill To: Contoso Worldwide, Inc.`. Compared with the label lowercased.
pub const PARTY_LABELS: &[&str] = &[
    "name",
    "by",
    "signed by",
    "prepared by",
    "prepared for",
    "issued by",
    "issued to",
    "to",
    "from",
    "attn",
    "attention",
    "dear",
    "client",
    "customer",
    "vendor",
    "supplier",
    "seller",
    "buyer",
    "purchaser",
    "contractor",
    "consultant",
    "employer",
    "employee",
    "landlord",
    "tenant",
    "lessor",
    "lessee",
    "licensor",
    "licensee",
    "borrower",
    "lender",
    "member",
    "insured",
    "named insured",
    "policyholder",
    "patient",
    "applicant",
    "carrier",
    "shipper",
    "consignee",
    "company",
    "bill to",
    "billed to",
    "sold to",
    "ship to",
    "remit to",
    "payable to",
    "owner",
    "account holder",
    "contact",
    "recipient",
    "sender",
    "addressee",
];

/// Words that make a label a number's: `Invoice No.`, `Policy Number`,
/// `PO #`, `Account`.
pub const IDENTIFIER_LABELS: &[&str] = &[
    "no",
    "number",
    "nbr",
    "num",
    "#",
    "id",
    "ref",
    "reference",
    "account",
    "acct",
    "policy",
    "claim",
    "case",
    "loan",
    "po",
    "file",
    "docket",
    "tracking",
    "pro",
    "bol",
];

/// Labels that make an amount a key fact: what is owed, lent or charged.
pub const AMOUNT_LABELS: &[&str] = &[
    "total",
    "amount due",
    "balance",
    "principal",
    "commitment",
    "rent",
    "price",
    "fee",
    "amount",
    "payment",
    "premium",
    "capital call",
    "purchase price",
    "net",
];

/// Section headings and what they say about the units under them, as the
/// retriever's section tags (`index::tag`).
pub const SECTION_TAG_WORDS: &[(&str, u16)] = &[
    ("definition", 1),
    ("term", 2),
    ("parties", 4),
    ("party", 4),
    ("recital", 8),
    ("whereas", 8),
    ("background", 8),
    ("preamble", 8),
    ("invoice", 16),
    ("bill to", 32),
    ("sold to", 32),
    ("ship to", 32),
    ("customer", 32),
    ("signature", 64),
    ("witness whereof", 64),
    ("executed", 64),
    ("notice", 128),
    ("schedule", 256),
    ("exhibit", 256),
    ("appendix", 256),
    ("annex", 256),
    ("payment", 512),
    ("fees", 512),
    ("compensation", 512),
    ("rent", 512),
    ("price", 512),
    ("scope", 1024),
    ("services", 1024),
    ("purpose", 1024),
    ("project", 1024),
    ("deliverables", 1024),
    ("description", 1024),
    ("summary", 1024),
];

/// Words too common to tell one unit from another for BM25.
pub const STOPWORDS: &[&str] = &[
    "the", "and", "of", "to", "in", "an", "for", "by", "on", "or", "as", "at", "be", "is", "are",
    "was", "were", "this", "that", "with", "from", "its", "it", "any", "all", "such", "shall",
    "will", "may", "which", "each", "other", "under", "upon", "herein", "hereof", "thereof", "has",
    "have", "not", "than", "into", "their", "there", "these", "those", "been", "being", "if", "so",
    "but", "per",
];
